# Travis-CI build script for sdsl-lite

language: cpp

cache:
  apt: true
  ccache: true

sudo: false

matrix:
  include:
    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" MYBUILD=Debug
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-4.9']

    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-4.9']

    - env: MYCC="gcc-5" MYCXX="g++-5" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-5']

    - env: MYCC="gcc-6" MYCXX="g++-6" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-6']

    - env: MYCC="gcc-7" MYCXX="g++-7" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-7']

    - env: MYCC="gcc-8" MYCXX="g++-8" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-8']

    - env: MYCC="clang" MYCXX="clang++" STDLIB=libc++
      os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version
  - cmake --version
  - ccache --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir sdsl-lite-build && cd sdsl-lite-build
  - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=$MYBUILD
  - make sdsl_test_targets -k -j 2
  - ctest -j 2 --output-on-failure
  - make sdsl_examples -k -j 2
  - make sdsl_tutorials -k -j 2

after_script:
  - ccache -s
